config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: :"callbacks#create"}
  root "static_pages#show", page: "home"

  get "static_pages/*page", to: "static_pages#show"
  resources :songs do
    resources :lyrics, only: [:index, :new, :create]
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :artists, except: :show
    resources :categories, except: :show
    resources :lyrics, only: :index
  end

  resources :users, only: :show
end

app/models/artist.rb
class Artist < ApplicationRecord
  acts_as_paranoid

  has_many :artist_songs
  has_many :songs, through: :artist_songs

  validates :name, presence: true, length: {minimum: 6}
  validates :gender, presence: true
  validates :type_of_music, presence: true
  validates :artist_type, presence: true

  enum gender: [:male, :female, :other]
  enum artist_type: [:singer, :composer]
  enum type_of_music: [:pop, :jazz, :rock, :balad, :rap, :another]
end

app/models/supports/artist.rb
class Supports::Artist
  attr_reader :artist

  def initialize artist
    @artist = artist
  end

  def genders
    @genders ||= Artist.genders.keys
  end

  def type_of_musics
    @type_of_musics ||= Artist.type_of_musics.keys
  end

  def artist_types
    @artist_types ||= Artist.artist_types.keys
  end
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < ApplicationController
  load_and_authorize_resource
  before_action :artist_support, only: [:new, :edit]
  def index
    @search = @artists.search params[:q]
    @artists = @search.result.paginate page: params[:page],
      per_page: Settings.artists.order_per_page
  end

  def show
  end

  def new
  end

  def create
    if @artist.save
      flash[:success] = t "flash.artists_create_success"
      redirect_to root_url
    else
      artist_support
      flash[:info] = t "flash.artists_create_failed"
      render :new
    end
  end

  def edit
  end

  def update
    if @artist.update_attributes artist_params
      flash[:success] = t "flash.artists_update_success"
      redirect_to admin_artists_url
    else
      artist_support
      flash[:danger] = t "flash.artists_update_failed"
      render :edit
    end
  end

  def destroy
    if @artist.destroy
      flash[:success] = t "flash.artists_destroy_success"
    else
      flash[:info] = t "flash.artists_destroy_failed"
    end
    redirect_to :back
  end

  private
  def artist_params
    params.require(:artist).permit :name, :gender, :date_of_birth,
      :type_of_music, :artist_type
  end

  def artist_support
    @support = Supports::Artist.new @artist
  end
end

app/views/admin/artists/_search_form.html.erb
<%= search_form_for @search, url: admin_artists_path do |f| %>
  <div class="form-group search_form">
    <%= f.label :name_cont, t(".search") %>
    <%= f.search_field :name_cont, placeholder: t(".placeholder"),
      class: "search_field" %>
  </div>
<% end %>

app/views/admin/artists/index.html.erb
<h1><%= t ".heading" %></h1>
<%= render "search_form" %>
<table class="table table-hover">
  <tr>
    <th><%= t ".artist_id" %></th>
    <th><%= t ".name" %></th>
    <th><%= t ".gender" %></th>
    <th><%= t ".date_of_birth" %></th>
    <th><%= t ".type_of_music" %></th>
    <th><%= t ".action" %></th>
  </tr>
  <% @artists.each_with_index do |artist, index| %>
    <tr>
      <td><%= @artists.offset + index + 1 %></td>
      <td><%= artist.name %></td>
      <td><%= artist.gender.capitalize %></td>
      <td><%= artist.date_of_birth %></td>
      <td><%= artist.type_of_music.capitalize %></td>
      <td>
        <%= link_to t(".delete_action"), admin_artist_path(artist.id),
          method: :delete, class: "label label-danger",
          data: {confirm: t(".confirm")} %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @artists %>

app/views/admin/artists/new.html.erb
<div class="row omb_login">
  <h3 class="omb_authTitle"><%= t ".heading" %></h3>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @artist] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="form-group">
        <%= f.label :name %><br/>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :gender %><br/>
        <%= f.select :gender,
          options_for_select(@support.genders),
          autofocus: true, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :type_of_music %><br/>
        <%= f.select :type_of_music,
          options_for_select(@support.type_of_musics),
          class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :artist_type %><br/>
        <%= f.select :artist_type,
          options_for_select(@support.artist_types),
          class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :date_of_birth %><br/>
        <%= f.text_field :date_of_birth, "data-behaviour": "datepicker",
          class: "form-control", required: true %>
      </div>
      <%= f.submit t(".submit"), class: "btn btn-primary btn-block btn-lg" %>
    <% end %>
  </div>
</div>