config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: :"callbacks#create"}
  root "static_pages#show", page: "home"

  get "static_pages/*page", to: "static_pages#show"
  resources :songs do
    resources :lyrics, only: [:index, :new, :create]
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :artists, except: :show
    resources :categories, except: :show
    resources :lyrics, only: :index
  end

  resources :users, only: :show
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :albums

  validates :name, presence: true, length: {maximum: 50}
end

app/models/supports/category.rb
class Supports::Category
  attr_reader :category

  def initialize category
    @category = category
  end
  
  def parents
    Category.all.map{|category| [category.name, category.id]}
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :category_support, only: [:new, :edit]

  def index
    @search = @categories.search params[:q]
    @categories = @search.result.all.paginate page:params[:page],
      per_page: Settings.categories.per_page
  end

  def new
  end

  def create
    if @category.save
      flash[:success] = t "flash.create_success"
      redirect_to admin_categories_path
    else
      category_support
      flash[:danger] = t "flash.create_failed"
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "flash.update_success"
      redirect_to admin_categories_path
    else
      category_support
      flash[:danger] = t "flash.update_failed"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "flash.destroy_success"
    else
      flash[:danger] = t "flash.destroy_failed"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :parent_id
  end

  def category_support
    @support = Supports::Category.new @category
  end
end

app/views/admin/categories/_category_form.html.erb
<%= form_for [:admin, @category], html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>
  </div> 
  <div class="form-group">
    <%= f.label :parent_id %><br/>
    <%= f.select :parent_id, options_for_select(@support.parents),
      {include_blank: t(".blank")}, class: "form-control" %>
  </div>
  <%= f.submit t(".submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/_search_form.html.erb
<%= search_form_for @search, url: admin_categories_path do |f| %>
  <div class="form-group search_form">
    <%= f.label :name_cont, t(".search") %>
    <%= f.search_field :name_cont, placeholder: t(".placeholder"),
      class: "search_field" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".heading" %></h1>
<%= render "category_form" %>

app/views/admin/categories/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".heading" %></h1>
<%= render "search_form" %>
<%= link_to t(".add"), new_admin_category_path,
  class: "btn btn-infor" %>
<table class="table table-hover">
  <tr>
    <th><%= t ".stt" %></th>
    <th><%= t ".name" %></th>
    <th><%= t ".parent_category" %></th>
    <th><%= t ".edit" %></th>
    <th><%= t ".delete" %></th>
  </tr>
  <% @categories.each_with_index do |category, index| %>
    <tr>
      <td> <%= @categories.offset + index + 1 %> </td>
      <td> <%= category.name %> </td>
      <td> <%= category.parent_id %> </td>
      <td>
        <%= link_to t(".edit"), edit_admin_category_path(category) %>	
      </td>
      <td>
        <%= link_to t(".delete"), admin_category_path(category),
          class: "btn btn-danger", method: :delete,
          data: {confirm: t(".confirm")} %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @categories %>

app/views/admin/categories/new.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".heading" %></h1>
<%= render "category_form" %>